GET http://localhost:3000/products/3

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "id": 4,
  "name": "New Product"
  
}

###
PUT http://localhost:3000/products/4
Content-Type: application/json

{
  "status": "sold out" 
  
}

###
DELETE http://localhost:3000/products/4


###
GET http://localhost:3000/images/cats.jpg
